console.log(toReadable(1));        // "one"
console.log(toReadable(997));      // "nine hundred ninety seven"
console.log(toReadable(100));      // "one hundred"
console.log(toReadable(101));      // "one hundred one"
console.log(toReadable(110));      // "one hundred ten"
console.log(toReadable(115));      // "one hundred fifteen"
console.log(toReadable(999));      // "nine hundred ninety nine"
